/**
 * Criteria loader for the Popcorn hook.
 * Reads and writes acceptance criteria from separate JSON files
 * in the test-plans/criteria/ directory. Criteria are decoupled
 * from test plans so they survive plan regeneration.
 */

import fs from 'node:fs/promises';
import path from 'node:path';

export interface CriteriaFile {
  flow: string;
  criteria: string[];
  autoGenerated?: boolean;
}

const DEFAULT_CRITERIA = ['All steps pass'];

/**
 * Loads acceptance criteria for a given flow from the criteria directory.
 * Falls back to the default criteria if no file exists.
 *
 * @param flowName - Name of the flow (matches the test plan name)
 * @param testPlansDir - Absolute path to the test-plans directory
 * @returns Array of criteria strings
 */
export async function loadCriteria(
  flowName: string,
  testPlansDir: string,
): Promise<string[]> {
  const criteriaDir = path.join(testPlansDir, 'criteria');
  const filePath = path.join(criteriaDir, `${flowName}.criteria.json`);

  try {
    const raw = await fs.readFile(filePath, 'utf-8');
    const parsed = JSON.parse(raw) as unknown;

    if (isValidCriteriaFile(parsed)) {
      return parsed.criteria.length > 0 ? parsed.criteria : DEFAULT_CRITERIA;
    }
  } catch {
    // File not found or invalid — use defaults
  }

  return DEFAULT_CRITERIA;
}

/**
 * Saves acceptance criteria for a flow to the criteria directory.
 * Creates the criteria directory if it doesn't exist.
 *
 * @param flowName - Name of the flow
 * @param criteria - Array of criteria strings
 * @param testPlansDir - Absolute path to the test-plans directory
 * @param autoGenerated - Whether the criteria were auto-generated
 */
export async function saveCriteria(
  flowName: string,
  criteria: string[],
  testPlansDir: string,
  autoGenerated = false,
): Promise<string> {
  const criteriaDir = path.join(testPlansDir, 'criteria');
  await fs.mkdir(criteriaDir, { recursive: true });

  const filePath = path.join(criteriaDir, `${flowName}.criteria.json`);
  const content: CriteriaFile = {
    flow: flowName,
    criteria,
    ...(autoGenerated ? { autoGenerated: true } : {}),
  };

  await fs.writeFile(filePath, JSON.stringify(content, null, 2) + '\n', 'utf-8');
  return filePath;
}

/**
 * Lists all flows that have saved criteria files.
 *
 * @param testPlansDir - Absolute path to the test-plans directory
 * @returns Array of flow names with saved criteria
 */
export async function listCriteriaFlows(
  testPlansDir: string,
): Promise<string[]> {
  const criteriaDir = path.join(testPlansDir, 'criteria');

  try {
    const entries = await fs.readdir(criteriaDir);
    return entries
      .filter((f) => f.endsWith('.criteria.json'))
      .map((f) => f.replace(/\.criteria\.json$/, ''));
  } catch {
    return [];
  }
}

function isValidCriteriaFile(data: unknown): data is CriteriaFile {
  if (typeof data !== 'object' || data === null || Array.isArray(data)) {
    return false;
  }
  const obj = data as Record<string, unknown>;
  return (
    typeof obj.flow === 'string' &&
    Array.isArray(obj.criteria) &&
    obj.criteria.every((c: unknown) => typeof c === 'string')
  );
}
